#!/usr/bin/env python3
"""slop.py — an LLM-facing CLI over the .slop.json primitives, so an agent (me) can
author/edit a cut without hand-writing JSON or re-reading the whole file. Mirrors the
editor's clip types + ripple semantics.

  python tools/slop.py overview  P.slop.json            # compact timeline (no JSON dump)
  python tools/slop.py add       P.slop.json --type code --start 50 --dur 8 -p title=... code=...
  python tools/slop.py insert    P.slop.json --type caption --at 30 --dur 3 -p text=Hi   # ripples after by dur
  python tools/slop.py set       P.slop.json CLIP start=12 dur=4 params.text="new" transform.pos=[0,30]
  python tools/slop.py mv        P.slop.json CLIP --to 20 [--ripple]      # or --by 2.5
  python tools/slop.py trim      P.slop.json CLIP --dur 6 [--no-ripple]   # right-edge; ripples after by default
  python tools/slop.py rm        P.slop.json CLIP [--ripple]
  python tools/slop.py ripple    P.slop.json --at 40 --by 3              # shift everything at/after t=40
  python tools/slop.py rebase    P.slop.json                            # slide so earliest start = 0

Notes: edits in place (--out to write elsewhere); preserves key order + unicode; clip ids
auto-generated by type if --id omitted; keyframe `t` values ripple with their clip."""
import argparse, json, collections, sys, re, os, subprocess
OD = collections.OrderedDict

# ── clip-type defaults: row + a sensible param skeleton (what the compositor reads) ──
ROW_OF = {"code":"r_code","caption":"r_cap","text":"r_cap","shape":"r_shape","gradient":"r_grade",
          "image":"r_img","video":"r_video","avatar":"r_av","tts":"r_vo","music":"r_music","blur":"r_blur",
          "diagram":"r_diagram","filler":"r_fill"}
TRACK_OF = {"r_code":("tk_code","Decompile","video"),"r_cap":("tk_cap","Captions","video"),
            "r_shape":("tk_shape","Callouts","video"),"r_grade":("tk_grade","Grade","video"),
            "r_img":("tk_img","Footage","video"),"r_video":("tk_video","Video","video"),
            "r_av":("tk_av","Gemma","video"),"r_blur":("tk_blur","Blur","video"),
            "r_diagram":("tk_diagram","Diagram","video"),"r_fill":("tk_fill","Backdrop","video"),
            "r_vo":("tk_vo","Narration","audio"),"r_music":("tk_music","Music","audio")}

PROJDIR = "."   # dir of the loaded project — plain uris resolve CWD-first, then here
                # (a project dir is portable: it can live outside the code repo)

def load(path):
    global PROJDIR
    PROJDIR = os.path.dirname(os.path.abspath(path))
    return json.load(open(path), object_pairs_hook=OD)

def resolve_uri(uri):
    """cache://→cache/, file:// stripped; plain relative paths try CWD then the project dir."""
    fp = (uri or "").replace("cache://", "cache/").replace("file://", "")
    if fp and not os.path.isabs(fp) and not os.path.exists(fp):
        pj = os.path.join(PROJDIR, fp)
        if os.path.exists(pj): return pj
    return fp
def save(p, path):
    json.dump(p, open(path,"w"), indent=2, ensure_ascii=False)

def jval(s):
    """parse a CLI value as JSON, falling back to a bare string."""
    try: return json.loads(s)
    except Exception: return s

def set_dotted(obj, dotted, value):
    """set a possibly-dotted key (params.text, transform.pos) into the clip dict."""
    parts = dotted.split(".")
    cur = obj
    for k in parts[:-1]:
        if k not in cur or not isinstance(cur[k], (dict, OD)): cur[k] = OD()
        cur = cur[k]
    cur[parts[-1]] = value

def order_index(p, rid):
    """draw-order index of a row (track order, top-first)."""
    flat = [r for t in p["tracks"] for r in t.get("rows",[])]
    return flat.index(rid) if rid in flat else 1e9

def ensure_row(p, rid):
    if rid in p["rows"]: return
    typ = next((t for t,r in ROW_OF.items() if r==rid), "image")
    p["rows"][rid] = OD([("type",typ),("name",rid),("params",OD()),("clips",[])])
    if not any(rid in t.get("rows",[]) for t in p["tracks"]):
        tid,name,kind = TRACK_OF.get(rid,(rid.replace("r_","tk_"),rid,"video"))
        p["tracks"].append(OD([("id",tid),("name",name),("kind",kind),("rows",[rid])]))

def ensure_row_after(p, rid, after, typ="image"):
    """like ensure_row but the new track slots right AFTER `after` in draw order (just below it),
    not at the bottom of the stack — overflow image rows (r_img2…) must stay in the content band."""
    if rid in p["rows"]: return
    p["rows"][rid]=OD([("type",typ),("name",rid),("params",OD()),("clips",[])])
    if not any(rid in t.get("rows",[]) for t in p["tracks"]):
        pos=next((i+1 for i,t in enumerate(p["tracks"]) if after in t.get("rows",[])),len(p["tracks"]))
        p["tracks"].insert(pos,OD([("id",rid.replace("r_","tk_")),("name",rid),("kind","video"),("rows",[rid])]))

def gen_id(p, typ):
    base = {"caption":"c_cap","text":"c_cap","code":"c_cd","shape":"c_sh","gradient":"c_vig",
            "image":"c_im","video":"c_vid","avatar":"c_av","tts":"v_","music":"c_mus","blur":"c_blur",
            "diagram":"c_diag","filler":"c_fill"}.get(typ,"c_")
    i=1
    while f"{base}{i}" in p["clips"]: i+=1
    return f"{base}{i}"

def new_clip(p, typ, row, start, dur, params, cid=None):
    cid = cid or gen_id(p, typ)
    ensure_row(p, row)
    c = OD([("row",row),("start",round(start,3)),("dur",round(dur,3)),
            ("params",OD(params)),
            ("transform",OD([("pos",[0,0]),("scale",[1.0,1.0]),("rot",0),("opacity",1),("anchor",[0.5,0.5])]))])
    if typ in ("image","video","avatar","tts","music"): c["asset"]=""
    p["clips"][cid]=c
    if cid not in p["rows"][row]["clips"]: p["rows"][row]["clips"].append(cid)
    return cid

def ensure_audio_row(p, rid="r_vidaud", name="Video Audio"):
    """An audio-kind row+track to hold video audio split out for advanced editing."""
    if rid not in p["rows"]:
        p["rows"][rid] = OD([("type","music"),("name",rid),("params",OD()),("clips",[])])
    if not any(rid in t.get("rows",[]) for t in p["tracks"]):
        p["tracks"].append(OD([("id","tk_vidaud"),("name",name),("kind","audio"),("rows",[rid])]))

# ── ripple (same semantics as the editor) ──
def shift_clip(c, d):
    c["start"] = round(c.get("start",0)+d, 3)
    for arr in c.get("keyframes",{}).values():
        for k in arr:
            if "t" in k: k["t"] = round(k["t"]+d, 3)

def ripple(p, pivot, d, except_id=None, after=True):
    for cid,c in p["clips"].items():
        if cid==except_id: continue
        s=c.get("start",0)
        if (s >= pivot-1e-6) if after else (s <= pivot+1e-6): shift_clip(c, d)

def rebase(p):
    if not p["clips"]: return 0
    mn=min(c.get("start",0) for c in p["clips"].values())
    if mn < -1e-6:
        for c in p["clips"].values(): shift_clip(c, -mn)
    return -mn if mn<0 else 0

def total(p): return max((c["start"]+c["dur"] for c in p["clips"].values()), default=0)

def add_asset(p, key, path):
    if key not in p["assets"]:
        p["assets"][key]=OD([("provider","external"),("type","image"),("status","ready"),("uri",path),("meta",OD())])

# ── scene templates: one command instantiates a good-looking, reusable scene (good defaults
# that auto-adapt) to interleave with ad-hoc scenes. Forward-compatible with richer host
# poses (swap --emotion / a future teacher sprite). ──
def _set_xform(c, pos=None, scale=None):
    if pos is not None: c["transform"]["pos"]=list(pos)
    if scale is not None: c["transform"]["scale"]=[scale,scale]

def template_explain(p, at, dur, shot, text, emotion, bg, pose):
    """Gemma in her room explaining, a framed screenshot floating beside her (not full-bg),
    she points at it; vignette tames the room; optional term caption. 1920x1080 defaults."""
    e=at+dur
    # background room (bottom track)
    if bg:
        add_asset(p,"bg_day","presets/backgrounds/room-day.png")
        ensure_row(p,"r_bg")
        if not any(t["id"]=="tk_bg" for t in p["tracks"]):  # bg lives at the BOTTOM (drawn first)
            p["tracks"].append(OD([("id","tk_bg"),("name","Background"),("kind","video"),("rows",["r_bg"])]))
        c=new_clip(p,"image","r_bg",at,dur,OD()); p["clips"][c]["asset"]="bg_day"; _set_xform(p["clips"][c],(0,0),1.5)
        p["clips"][c]["notes"]="explain template — room bg"
    # vignette to tame the busy room, bright spot on the host (lower-left)
    cg=new_clip(p,"gradient","r_grade",at,dur,OD([("gradient","vignette"),("color",[8,6,16,255]),
        ("strength",0.5),("feather",0.5),("anchor",[0.22,0.62])])); p["clips"][cg]["notes"]="explain template — vignette"
    # floating framed screenshot, upper-right (not covering the whole bg)
    POS=(470,-150)
    ci=new_clip(p,"image","r_img2",at,dur,OD()); p["clips"][ci]["asset"]=shot; _set_xform(p["clips"][ci],POS,0.38)
    p["clips"][ci]["notes"]="explain template — floating screenshot"; apply_transition(p,ci,"pop",0.6,True)
    cf=new_clip(p,"shape","r_shape",at,dur,OD([("shape","box"),("w",760),("h",430),
        ("color",[245,245,250,255]),("thickness",6),("round",10)])); _set_xform(p["clips"][cf],POS);
    p["clips"][cf]["notes"]="explain template — screen bezel"; apply_transition(p,cf,"pop",0.6,True)
    # host lower-left, points at the screen (arrow stand-in until a teacher-pose sprite exists)
    ca=new_clip(p,"avatar","r_av",at,dur,OD([("emotion",emotion),("dim",0.8),("lightup",0.34),
        ("talk_bob",0.7),("talk_scale",0.4)])); _set_xform(p["clips"][ca],(-560,150),0.6)
    p["clips"][ca]["notes"]=f"explain template — host (pose={pose}); generate visemes"; apply_transition(p,ca,"rise",0.7,False)
    car=new_clip(p,"shape","r_shape",at+0.5,dur-0.5,OD([("shape","arrow"),("from",[-330,30]),("to",[120,-130]),
        ("color",[244,191,79,255]),("thickness",9),("grow",1.0)])); p["clips"][car]["notes"]="explain template — pointing"
    apply_transition(p,car,"fade",0.4,True)
    # optional term caption
    if text:
        cc=new_clip(p,"caption","r_cap",at+0.4,dur-0.6,OD([("style","term"),("text",text),("font_px",40),
            ("accent",[198,120,221,255])])); _set_xform(p["clips"][cc],(430,-330)); apply_transition(p,cc,"drop-soft",0.6,True)
    return [c for c in (ca,ci,cf,cg) ]

TEMPLATES={"explain": template_explain}

# ── transition presets (reusable entrance easing) ──
# CRITICAL: the eval uses the LEFT keyframe's interp to drive a segment, so the easing/spring
# goes on the START keyframe (offset) → END keyframe (resting). Springs give the easing:
# critically-damped = smooth ease-out (no overshoot); underdamped = bounce.
def _kf(t, v, interp=None, spring=None):
    d = OD([("t", round(t, 3)), ("v", v)])
    if interp: d["interp"] = interp
    if spring: d["spring"] = OD([("stiffness", spring[0]), ("damping", spring[1])])
    return d
PRESETS = {  # axis/off = positional offset to enter from; spring=[stiffness,damping]
    "drop-soft":   {"axis": "y", "off": -130, "spring": [110, 21]},   # quick drop, smooth settle, no bounce
    "drop-bounce": {"axis": "y", "off": -130, "spring": [190, 11]},   # drop + overshoot/bounce
    "rise":        {"axis": "y", "off":  90,  "spring": [130, 23]},   # slide up into place
    "slide-l":     {"axis": "x", "off": -420, "spring": [130, 22]},
    "slide-r":     {"axis": "x", "off":  420, "spring": [130, 22]},
    "pop":         {"scale": 0.5, "spring": [240, 15]},               # scale up with a little overshoot
    "fade":        {},                                                # opacity only
}
def apply_transition(p, cid, preset, indur=0.9, do_out=True):
    c = p["clips"][cid]; tf = c.get("transform", {})
    pos = list(tf.get("pos", [0, 0])); scl = list(tf.get("scale", [1, 1]))
    s = c["start"]; e = s + c["dur"]; P = PRESETS[preset]
    kfs = c.setdefault("keyframes", OD())
    for k in ("transform.pos", "transform.scale", "transform.opacity"): kfs.pop(k, None)  # replace stale transform anim
    if P.get("axis") == "y":
        kfs["transform.pos"] = [_kf(s, [pos[0], pos[1] + P["off"]], "spring", P["spring"]), _kf(s + indur, pos)]
    elif P.get("axis") == "x":
        kfs["transform.pos"] = [_kf(s, [pos[0] + P["off"], pos[1]], "spring", P["spring"]), _kf(s + indur, pos)]
    elif "scale" in P:
        kfs["transform.scale"] = [_kf(s, [scl[0]*P["scale"], scl[1]*P["scale"]], "spring", P["spring"]), _kf(s + indur, scl)]
    op = [_kf(s, 0.0, "bezier"), _kf(s + min(0.4, indur), 1.0)]
    if do_out and e - s > 1.0: op += [_kf(e - 0.4, 1.0, "bezier"), _kf(e, 0.0, "bezier")]
    kfs["transform.opacity"] = op

# ── overview: compact timeline (structured + ascii lanes) ──
def desc_of(c):
    pr=c.get("params",{})
    for k in ("text","prompt","code","title","mood","sub","gradient","shape","emotion"):
        if k in pr and pr[k] not in ("",None):
            v=str(pr[k]).replace("\n"," "); return f"{k}={v[:46]!r}"
    return f"asset={c['asset']}" if c.get("asset") else ""

def cmd_overview(p, args):
    print(f"# {p['meta'].get('title','?')}  {p['meta'].get('resolution')}  {p['meta'].get('fps')}fps  "
          f"total {total(p):.1f}s  ({len(p['clips'])} clips)")
    W=90; dur=max(total(p),0.1)
    for t in p["tracks"]:
        for rid in t.get("rows",[]):
            r=p["rows"].get(rid,{})
            clips=sorted([(cid,p["clips"][cid]) for cid in r.get("clips",[]) if cid in p["clips"]],
                         key=lambda kv: kv[1].get("start",0))
            # ascii lane
            lane=[" "]*W
            for cid,c in clips:
                a=int(c["start"]/dur*W); b=max(a, int((c["start"]+c["dur"])/dur*W)-1)
                for x in range(max(0,a),min(W,b+1)): lane[x]="="
                if a<W: lane[a]="["
                if b<W: lane[b]="]"
            print(f"\n{rid:9s} {r.get('type','?'):8s} |{''.join(lane)}|")
            for cid,c in clips:
                kf="+kf" if c.get("keyframes") else ""
                print(f"   {c['start']:7.2f}-{c['start']+c['dur']:7.2f} {cid:12s} {desc_of(c)}{kf}")

# ── skeleton: compile a BEAT LIST into a full project (the LLM authoring surface) ──
# A beat = one VO line + (optionally) a visual change. Visuals PERSIST until the next beat
# that sets one ("hold" is the default), so "a gap with no visuals" cannot be authored.
# Media placement uses the render-time `layout` primitive (inset/fullscreen/fit) — no transforms.
# Timing is ESTIMATED from text length; run `genvo` (or the editor) then `retime` to snap the
# whole timeline to the real VO durations.
#
# skeleton file:
#   { "title": "...", "resolution": [1920,1080], "fps": 30,
#     "voice": "gemma-san-deep-clone", "rig": "gemma-big",
#     "bg": "presets/backgrounds/room-day.png",          // standing set behind host-only beats
#     "bg_dark": "presets/backgrounds/room-dark.png",    // the gag/outro variant ("host-dark")
#     "beats": [
#       {"line": "...", "emotion": "smug"},                              // no visual → HOLD previous
#       {"line": "...", "visual": "host"},                               // host-only (content clears; room bg)
#       {"line": "...", "visual": "host-dark"},                          // host in the DARK room (gags/outro)
#       {"line": "...", "visual": "host-dark", "gag": "clueless"},       // + the deadpan arrow/"clueless" callout
#       {"line": "...", "visual": {"image": "path.png"}},                // inset (default layout; pops in)
#       {"line": "...", "visual": {"image": "p.png", "layout": "fullscreen"}},
#       {"line": "...", "visual": {"video": "p.mp4", "in": 12.0, "layout": "inset"}},
#       {"line": "...", "visual": {"stack": ["a.png","b.png"], "side": "center"|"right"}},  // 2 stacked, padded
#       {"line": "...", "visual": {"code": "int main(){}", "lang": "c", "title": "main.c"}}, // docks top, auto-fit font,
#                                                                        // host small lower-right (code/diagram/stack)
#       {"line": "...", "visual": {"caption": "BIG TEXT", "sub": "small text"}},  // plate → least-busy corner;
#                                                                        // caption-only beats keep the ROOM bg (no bare fill)
#       {"line": "...", "visual": {"diagram": {...draw_diagram params...}}},      // card+autofit; traffic/dead animate
#       {"line": "...", "solo": true, "visual": {...}},                  // no host this beat (readable full-width shots)
#       {"section": "Act 2"},                                            // blur-swap scene cut
#       {"pause": 0.8} ] }
CPS = 0.062     # est seconds per character of VO text (~16 cps) — retime fixes the truth later
GAP = 0.35      # breathing room between lines
def est_dur(text): return max(1.2, round(len(text)*CPS+0.4, 2))

def cmd_skeleton(a):
    sk=load(a.skeleton)
    p=OD([("schema","slopstudio.project/1"),
          ("meta",OD([("title",sk.get("title","untitled")),("fps",sk.get("fps",30)),
                      ("resolution",sk.get("resolution",[1920,1080])),("sample_rate",48000),
                      ("vignette",sk.get("vignette",0.26)),
                      ("notes","compiled by slop.py skeleton from "+os.path.basename(a.skeleton))])),
          ("assets",OD()),("tracks",[]),("rows",OD()),("clips",OD())])
    voice=sk.get("voice","gemma-san-deep-clone"); rig=sk.get("rig","gemma-big")
    # rows in draw order (top-first): captions/callouts > HOST > code/diagram > content > blur > bg > filler
    # (the host draws OVER side-showcase images AND code/diagram cards — she overlaps content,
    # content never covers her; only captions/plates and the gag arrow sit above her)
    for rid in ("r_cap","r_shape","r_av","r_code","r_diagram","r_img","r_video","r_blur","r_bg","r_fill","r_vo"):
        if rid=="r_bg":
            p["rows"][rid]=OD([("type","image"),("name","Background"),("params",OD()),("clips",[])])
            p["tracks"].append(OD([("id","tk_bg"),("name","Background"),("kind","video"),("rows",[rid])]))
        else: ensure_row(p,rid)
    p["rows"]["r_vo"]["params"]=OD([("voice_preset",voice),("normalize",True)])
    p["rows"]["r_av"]["params"]=OD([("rig",rig),("driven_by","r_vo")])
    akeys={}   # uri -> asset key (dedupe; repeats become visible to lint)
    def asset_for(uri, typ):
        if uri in akeys: return akeys[uri]
        k=f"as{len(akeys)+1:02d}_"+re.sub(r"[^a-z0-9]+","",os.path.basename(uri).rsplit(".",1)[0].lower())[:16]
        p["assets"][k]=OD([("provider","external"),("type",typ),("status","ready"),("uri",uri),("meta",OD())])
        akeys[uri]=k; return k
    t=0.0; bi=0
    held_kind=None              # what the held visual is: "card" (code/diagram/stack) | "media" | None
    open_vis=[]                 # clip ids of the held visual(s) — extend until the next visual change
    open_fill=None              # filler under the current content run
    bg_open=0.0                 # the room bg backs HOST + plate-only spans — bare fill-only host shots are unauthorable
    bg_variant="day"
    bg_spans=[]                 # (t0, t1, variant)
    sections=[]
    def close_vis(at):
        nonlocal open_vis, open_fill
        for cid in open_vis:
            c=p["clips"][cid]; c["dur"]=round(max(0.4, at-c["start"]),3)
        open_vis=[]
        if open_fill:
            c=p["clips"][open_fill]; c["dur"]=round(max(0.4, at-c["start"]),3); open_fill=None
    def close_bg(at):
        nonlocal bg_open
        if bg_open is not None and at-bg_open>0.05: bg_spans.append((bg_open, at, bg_variant))
        bg_open=None
    def open_bg(at, variant):
        nonlocal bg_open, bg_variant
        if bg_open is not None and variant!=bg_variant: close_bg(at)
        if bg_open is None: bg_open=at
        bg_variant=variant
    def img_dims(uri):
        try:
            from PIL import Image
            return Image.open(uri).size
        except Exception: return None
    def img_covers(uri):
        """cover-fullscreen keeps enough of the image? (a 5:1 banner shouldn't cover)"""
        d=img_dims(uri)
        if not d: return True
        ar=(d[0]/d[1])/(16/9)
        return (1/ar if ar>1 else ar) >= 0.45
    for b in sk.get("beats",[]):
        if "section" in b:
            # scene cut: blur-swap straddling the boundary + a marker note + a branded act card
            # (a small pill in the least-busy corner for the first seconds of the act)
            cb=new_clip(p,"blur","r_blur",max(0.0,t-0.55),1.1,OD(),f"cut{len(sections)+1:02d}")
            p["clips"][cb]["notes"]="section: "+str(b["section"]); sections.append((t,b["section"]))
            stc=new_clip(p,"caption","r_cap",t+0.2,3.4,
                         OD([("style","term"),("text",f"ACT {len(sections)} · {str(b['section']).upper()}"),
                             ("font_px",34),("place","auto"),("transition",OD([("in","pop")]))]),
                         f"cut{len(sections):02d}_title")
            continue
        if "pause" in b:
            t=round(t+float(b["pause"]),3); continue
        line=b.get("line","")
        dur=float(b.get("dur", est_dur(line))) if (line or "dur" in b) else float(b.get("dur",2.0))
        bi+=1; pref=f"b{bi:02d}"
        emo=b.get("emotion","neutral")
        if line:
            cv=new_clip(p,"tts","r_vo",t,dur,OD([("text",line),("emotion",emo),("voice_preset",voice)]),f"{pref}_vo")
            p["clips"][cv]["notes"]=line[:60]
            if not b.get("solo"):   # solo:true = no host this beat (readable full-width shots, e.g. the apology)
                ca=new_clip(p,"avatar","r_av",t,dur+GAP,OD([("emotion",emo),("framing",b.get("framing","bust"))]),f"{pref}_av")
        def make_visual(v, at, vdur, sfx=""):
            """one visual spec → clip(s). Returns (clip_ids, needs_filler)."""
            lay=v.get("layout","inset")
            zoom=float(v.get("zoom",1.0))    # ×fit — "make the relevant part big" (credits closeups etc.)
            cid=None; fill=True
            if "image" in v:
                uri=v["image"]
                if lay=="fullscreen" and not img_covers(uri): lay="fit"   # wide banner: contain over the filler
                cid=new_clip(p,"image","r_img",at,vdur,OD([("layout",lay),("motion","zoom_in"),("auto_grade",True)]),f"{pref}{sfx}_img")
                p["clips"][cid]["asset"]=asset_for(uri,"image")
                fill = lay!="fullscreen"
            elif "video" in v:
                prm=OD([("layout",lay),("in",float(v.get("in",0.0))),("video_volume",v.get("volume",0.12)),("loop",True)])
                cid=new_clip(p,"video","r_video",at,vdur,prm,f"{pref}{sfx}_vid")
                p["clips"][cid]["asset"]=asset_for(v["video"],"video")
                fill = lay!="fullscreen"
            elif "stack" in v:
                # multiple images shown together — zoom-crop pairs (menu bar + tasks), a banner +
                # the site under it, a collage of wallpapers/savers. side:"center" = 2 stacked big,
                # near-full-width; "right" = the content column beside the host; "left" (or n>2) =
                # a left-anchored CASCADE: slightly overlapped cells, even margin from the left
                # edge, host presenting from the right. Each item lands on its OWN image row
                # (r_img top, r_img2… just below — deterministic z: FIRST item on top, never two
                # overlapping clips on one track) and pops in STAGGERED (the unveil).
                items=[it if isinstance(it,dict) else {"image":it} for it in v["stack"]]
                n=max(1,len(items)); cids=[]
                side=v.get("side","center")
                cascade = side=="left" or n>2
                CASCADE={2:[(-430,-220),(-90,210)],
                         3:[(-520,-250),(-90,-250),(-305,230)],
                         4:[(-520,-250),(-90,-250),(-520,230),(-90,230)]}
                # banner + main (a site header over the site itself): the extreme-aspect item rides
                # top-right ON TOP, the main shot goes BIG center-left (user-tuned ruputer-fan layout)
                dims=[img_dims(it["image"]) or (1280,720) for it in items]
                bannerIdx=None
                if n==2 and not cascade:
                    wide=[i for i,d in enumerate(dims) if d[0]/max(1,d[1])>3.0]
                    if len(wide)==1: bannerIdx=wide[0]
                for ii,it in enumerate(items):
                    uri=it["image"]; d=dims[ii]
                    if bannerIdx is not None:
                        if ii==bannerIdx: maxw,maxh=490.0,240.0; pos=(400.0,-236.0)
                        else:             maxw,maxh=1430.0,1030.0; pos=(-227.0,0.0)
                    elif cascade:
                        maxw,maxh=800.0,450.0
                        pos=CASCADE.get(min(n,4),CASCADE[4])[min(ii,3)]
                    elif side=="right": maxw,maxh=845.0,430.0; pos=(400.0, round((ii-(n-1)/2)*(maxh+42)))
                    else:               maxw,maxh=1620.0,455.0; pos=(0.0, round((ii-(n-1)/2)*(maxh+42)))
                    sc=min(maxw/d[0], maxh/d[1])*float(it.get("zoom",1.0))
                    rid="r_img" if ii==0 else f"r_img{ii+1}"
                    if ii: ensure_row_after(p, rid, "r_img" if ii==1 else f"r_img{ii}")
                    stag=min(0.35*ii, max(0.0, vdur-1.5))          # staggered unveil (pop, pop, pop…)
                    scid=new_clip(p,"image",rid,round(at+stag,3),round(vdur-stag,3),
                        OD([("motion","none"),("auto_grade",True),
                        ("transition",OD([("in","pop")]))]),f"{pref}{sfx}_st{ii+1}")
                    p["clips"][scid]["asset"]=asset_for(uri,"image")
                    _set_xform(p["clips"][scid],pos, round(sc,4))
                    cids.append(scid)
                return cids, True
            elif "code" in v:
                # pass EVERY code key through (highlight/line_numbers/first_line…). Defaults: the card
                # docks TOP, auto-fits its font to the frame width (drop font_px to opt in), and the
                # host goes small lower-right — the code owns the frame.
                prm=OD((k,val) for k,val in v.items() if k not in ("layout","zoom","for"))
                if "dock" not in prm: prm["dock"]="top"
                cid=new_clip(p,"code","r_code",at,vdur,prm,f"{pref}{sfx}_code")
            elif "caption" in v:
                prm=OD([("text",v["caption"]),("style",v.get("style","lower_third"))])
                if "sub" in v: prm["sub"]=v["sub"]
                if "accent" in v: prm["accent"]=v["accent"]
                cid=new_clip(p,"caption","r_cap",at,vdur,prm,f"{pref}{sfx}_cap")
                # placement is render-time: lower_third defaults to the bottom STRAP away from the
                # host, jp_lesson to big-centered-low with the host stepping aside (both distilled
                # from user tweaks); term plates pin to the least-busy TOP corner via place:auto.
                if prm["style"] not in ("jp_lesson","lower_third"): prm["place"]="auto"
            elif "diagram" in v:
                cid=new_clip(p,"diagram","r_diagram",at,vdur,OD(v["diagram"]),f"{pref}{sfx}_diag")
                _set_xform(p["clips"][cid],(0,-60))     # centered card (auto-fits width; host goes small)
            if cid and zoom!=1.0:
                tf=p["clips"][cid]["transform"]; tf["scale"]=[tf["scale"][0]*zoom, tf["scale"][1]*zoom]
            return ([cid] if cid else []), fill
        scene=b.get("scene")     # "dark"/"day": force the ROOM as the backdrop even under media (gag scenes)
        if scene: open_bg(t, scene)
        vis=b.get("visual")
        if vis is not None:
            close_vis(t)
            if vis in ("host","host-dark"):
                open_bg(t, "dark" if vis=="host-dark" else "day")   # solo/reaction beat → the room set
                held_kind=None
            else:
                seq = vis if isinstance(vis,list) else [vis]
                # plate-only beats KEEP the room set (a plate over the bare fill gradient reads empty —
                # "either images or a shot in the room"); media/cards close it for the filler backdrop.
                cap_only = all("caption" in v for v in seq)
                if scene: pass                                       # scene beats keep the forced room
                elif cap_only: open_bg(t, bg_variant if bg_open is not None else "day")
                else: close_bg(t)
                # sequential swap inside one beat: items with "for" take that long, the rest split evenly
                fixed=sum(float(v.get("for",0)) for v in seq)
                nfree=sum(1 for v in seq if "for" not in v)
                free=max(0.6,(dur+GAP-fixed)/nfree) if nfree else 0
                at=t
                for si,v in enumerate(seq):
                    vdur=float(v.get("for",free))
                    if si: close_vis(at)                 # end the previous sub-visual + its filler
                    sfx=f"s{si}" if len(seq)>1 else ""
                    cids,fill=make_visual(v,at,vdur,sfx)
                    if cids:
                        open_vis=cids
                        if fill and not cap_only and not scene:      # a scene beat's backdrop IS the room
                            open_fill=new_clip(p,"filler","r_fill",at,vdur,OD(),f"{pref}{sfx}_fill")
                    at=round(at+vdur,3)
                held_kind = "card" if any(k in v for v in seq for k in ("code","diagram","stack")) else "media"
                # code sections get the strict-teacher pose on the beat that reveals the card
                if line and not b.get("solo") and any("code" in v for v in seq):
                    p["clips"][f"{pref}_av"]["params"]["emotion"]="teaching"
        # data-dense cards (code/diagram/stack) own the frame — while one is up (incl. HOLD beats)
        # the host goes small in the lower-right, flipped to face the content.
        if held_kind=="card" and line and not b.get("solo"):
            av=p["clips"][f"{pref}_av"]
            av["params"]["framing"]="bust"; av["params"]["face"]="left"
            av["transform"]["pos"]=[660,320]; av["transform"]["scale"]=[0.62,0.62]
        # plate: a corner caption drawn WITH the beat's (or the held) visual — not a visual change
        if b.get("plate") and line:
            pl=b["plate"]
            prm=OD([("text",pl.get("caption") or pl.get("text","")),("style",pl.get("style","term")),("place","auto")])
            if "sub" in pl: prm["sub"]=pl["sub"]
            new_clip(p,"caption","r_cap",t+0.3,dur+GAP-0.3,prm,f"{pref}_plate")
        # gag:"clueless" — the deadpan callout: an arrow at the host + the label, slightly delayed.
        # With side content on screen the host presenter-shifts LEFT, so the callout follows her.
        if b.get("gag")=="clueless" and line:
            hasMedia = isinstance(vis,(dict,list))
            # Label + arrow sit clearly OFF her face (user-corrected geometry): the label rides the
            # upper corner on her free side and the arrow stops ~300px short of the face, pointing at
            # it. host-only → she's centered, callout up-right; with media she presenter-shifts LEFT
            # → callout mirrored up-left of her.
            cpos,afrom,ato = ((-780,-379),[-763,-372],[-660,-212]) if hasMedia else ((454,-379),[437,-372],[297,-212])
            gc=new_clip(p,"caption","r_cap",t+0.35,dur+GAP-0.35,
                        OD([("style","term"),("text","clueless"),("transition",OD([("in","pop")]))]),f"{pref}_gagcap")
            _set_xform(p["clips"][gc],cpos)
            ga=new_clip(p,"shape","r_shape",t+0.35,dur+GAP-0.35,
                        OD([("shape","arrow"),("from",afrom),("to",ato),
                            ("color",[244,191,79,255]),("thickness",11)]),f"{pref}_gagarr")
            p["clips"][ga]["keyframes"]=OD([("params.grow",[_kf(t+0.4,0.0,"bezier"),_kf(t+0.75,1.0)])])
        t=round(t+ (dur+GAP if line else dur),3)
    close_vis(t)
    close_bg(t)
    tot=t
    # The room bg must SURVIVE a section blur-swap: a bg span that ends at the section boundary
    # vanishes at peak blur (a sudden colour change mid-transition — user-reported). Extend it to
    # the blur's END with a slow fade-out, so the room dissolves into the next backdrop UNDER the
    # blur. (Fillers are already contiguous by construction — the next beat opens its own.)
    sec_ts=[st for st,_ in sections]
    def blur_extend(end):
        for ts in sec_ts:
            if ts-0.7 <= end <= ts+0.1: return ts+0.6
        return end
    if sk.get("bg"):   # the standing set backs HOST + plate-only spans; content beats get the filler gradient
        dark=sk.get("bg_dark","presets/backgrounds/room-dark.png")
        for si,(b0,b1,var) in enumerate(bg_spans):
            b1x=blur_extend(b1)
            prm=OD([("layout","fullscreen"),("motion","none"),("saturation",0.95)])
            if b1x>b1: prm["transition"]=OD([("out",OD([("type","fade"),("dur",0.8)]))])
            cb=new_clip(p,"image","r_bg",round(b0,3),round(b1x-b0,3),prm,f"c_bg{si+1:02d}")
            p["clips"][cb]["asset"]=asset_for(dark if var=="dark" else sk["bg"],"image")
    if sk.get("music"):
        cm=new_clip(p,"music","r_music",0.0,round(tot,3),OD([("gain_db",-16)]),"c_music")
        p["clips"][cm]["asset"]=asset_for(sk["music"],"music")
        p["assets"][akeys[sk["music"]]]["type"]="music"
    save(p,a.out or a.skeleton.replace(".skeleton.json","")+".slop.json")
    print(f"compiled {bi} beats -> {a.out}  (est {tot:.1f}s; {len(sections)} sections)")
    print("next: python tools/slop.py genvo "+ (a.out or "<project>") +"   # generate VO + visemes, snap timing")

# ── lint: catch the known LLM-authoring failure modes on ANY project ──
def _spans(p, rows):
    """merged active spans of clips on rows of the given types."""
    sp=[]
    for cid,c in p["clips"].items():
        rt=p["rows"].get(c.get("row",""),{}).get("type")
        if rt in rows: sp.append((c["start"], c["start"]+c["dur"]))
    sp.sort()
    out=[]
    for s,e in sp:
        if out and s<=out[-1][1]+1e-6: out[-1][1]=max(out[-1][1],e)
        else: out.append([s,e])
    return out

def cmd_lint(p, a):
    warn=[]; info=[]
    tot=total(p)
    vo=_spans(p,("tts",))
    vis=_spans(p,("image","video","code","caption","diagram","shape"))
    # 1. narration with NOTHING on screen but the host/bg (fine) — vs literally nothing
    allvis=_spans(p,("image","video","code","caption","diagram","shape","avatar","gradient","filler"))
    def gaps(cover, lo, hi, min_gap):
        g=[]; cur=lo
        for s,e in cover:
            if s-cur>min_gap: g.append((cur,s))
            cur=max(cur,e)
        if hi-cur>min_gap: g.append((cur,hi))
        return g
    for s,e in gaps(allvis,0,tot,0.25):
        warn.append(f"BLACK {s:7.2f}-{e:7.2f}  nothing at all on screen")
    for vs,ve in vo:
        for s,e in gaps([ (max(s0,vs),min(e0,ve)) for s0,e0 in vis if e0>vs and s0<ve ], vs, ve, 3.0):
            info.append(f"talky {s:7.2f}-{e:7.2f}  narration with no content visual (host-only; fine if intended)")
    # 2. visual repeats: same asset in many clips / back-to-back
    by_asset={}
    for cid,c in sorted(p["clips"].items(), key=lambda kv: kv[1].get("start",0)):
        if c.get("row")=="r_bg": continue      # the standing set backs many spans by design
        rt=p["rows"].get(c.get("row",""),{}).get("type")
        if rt in ("image","video") and c.get("asset"): by_asset.setdefault(c["asset"],[]).append(cid)
    for ak,cids in by_asset.items():
        if len(cids)>3: warn.append(f"REPEAT asset '{ak}' used by {len(cids)} clips: {', '.join(cids[:6])}")
    # 3. missing files — only for assets a clip actually REFERENCES (regens orphan old entries)
    refd={c.get("asset") for c in p["clips"].values() if c.get("asset")}
    for ak,ad in p.get("assets",{}).items():
        if ak not in refd: continue
        uri=ad.get("uri","")
        if not uri:
            if ad.get("status")!="ready": warn.append(f"ASSET '{ak}' not generated (status={ad.get('status')})")
            continue
        if not os.path.exists(resolve_uri(uri)): warn.append(f"MISSING '{ak}' -> {uri}")
    # 4. stale VO: clip text != generated asset text
    for cid,c in p["clips"].items():
        if p["rows"].get(c.get("row",""),{}).get("type")!="tts": continue
        ak=c.get("asset"); ad=p.get("assets",{}).get(ak) if ak else None
        ct=c.get("params",{}).get("text","")
        if ad and ct and ad.get("params",{}).get("text","") not in ("",ct,_tts_norm(ct)):
            warn.append(f"STALE-VO {cid}: clip text changed since gen ('{ct[:40]}...' vs asset)")
        if ad and ad.get("meta",{}).get("duration"):
            # a split take (params.in / shared asset) plays a WINDOW of the audio — check the
            # window fits instead of demanding dur == full audio (retime leaves splits alone)
            inpt=c.get("params",{}).get("in")
            nshare=sum(1 for c2 in p["clips"].values()
                       if c2.get("asset")==ak and p["rows"].get(c2.get("row",""),{}).get("type")=="tts")
            if inpt is not None or nshare>1:
                if (inpt or 0)+c["dur"] > ad["meta"]["duration"]+0.25:
                    warn.append(f"SPLIT-OVERRUN {cid}: in {inpt or 0:.2f}+dur {c['dur']:.2f} > audio {ad['meta']['duration']:.2f}s (plays silence)")
            elif abs(c["dur"]-ad["meta"]["duration"])>0.25:
                info.append(f"desync {cid}: dur {c['dur']:.2f}s vs audio {ad['meta']['duration']:.2f}s (run retime)")
        if not ad and ct: warn.append(f"NO-VO {cid}: line not generated yet ('{ct[:40]}')")
    # 4b. clips starting before t=0 (export starts at 0 — they play truncated)
    for cid,c in p["clips"].items():
        if c.get("start",0) < -0.01: warn.append(f"NEGATIVE {cid} starts at {c['start']:.2f}s (before 0)")
    # 5. same-row overlaps — audio doubles up (warn); visuals may be intentional side-by-side (info)
    for rid,r in p["rows"].items():
        cs=sorted([p["clips"][c] for c in r.get("clips",[]) if c in p["clips"]], key=lambda c:c["start"])
        audio=r.get("type") in ("tts","music")
        for i in range(1,len(cs)):
            ov=cs[i-1]["start"]+cs[i-1]["dur"]-cs[i]["start"]
            if ov>0.05:
                m=f"OVERLAP on {rid}: clips overlap by {ov:.2f}s at {cs[i]['start']:.2f}"
                (warn if audio else info).append(m if audio else m+" (fine if side-by-side)")
    # 6. emotions that won't resolve in the rig (fall back to neutral — usually fine, listed FYI)
    rigs={r.get("params",{}).get("rig") for r in p["rows"].values() if r.get("type")=="avatar"}
    for rig in filter(None,rigs):
        mani=os.path.join("presets","avatars",rig,"manifest.json")
        if not os.path.exists(mani): continue
        exprs=set(json.load(open(mani)).get("expressions",{}).keys())
        missing={}
        for cid,c in p["clips"].items():
            if p["rows"].get(c.get("row",""),{}).get("type")!="avatar": continue
            emo=c.get("params",{}).get("emotion","")
            if emo and emo not in ("auto",) and emo.split(",")[0].strip() not in exprs:
                missing.setdefault(emo,[]).append(cid)
        for emo,cids in missing.items():
            info.append(f"emotion '{emo}' not in rig {rig} ({len(cids)} clips) -> falls back")
    for w in warn: print("WARN ",w)
    for i in info: print("info ",i)
    print(f"lint: {len(warn)} warnings, {len(info)} notes  ({len(p['clips'])} clips, {tot:.1f}s)")
    return 1 if warn else 0

# ── retime: piecewise time-warp the WHOLE timeline so each beat matches its real VO duration ──
def cmd_retime(p, a):
    vos=sorted([(cid,c) for cid,c in p["clips"].items()
                if p["rows"].get(c.get("row",""),{}).get("type")=="tts"], key=lambda kv: kv[1]["start"])
    if not vos: print("retime: no VO clips"); return
    # a SPLIT take (params.in set, or several clips sharing one speech asset — the user cut a
    # line for a mid-sentence pause) is authored timing: retime must never resize it back to
    # the full audio duration (that corruption stranded the chiyo-key beat once already).
    shared={}
    for _,c in vos: shared[c.get("asset")]=shared.get(c.get("asset"),0)+1
    def is_split(c):
        return c.get("params",{}).get("in") is not None or shared.get(c.get("asset"),0)>1
    oldB=[c["start"] for _,c in vos]+[max(total(p), vos[-1][1]["start"]+vos[-1][1]["dur"])]
    newB=[oldB[0]]
    for i,(cid,c) in enumerate(vos):
        ad=p.get("assets",{}).get(c.get("asset",""),{})
        actual=None if is_split(c) else ad.get("meta",{}).get("duration")
        span=oldB[i+1]-oldB[i]
        newspan=span+(actual-c["dur"]) if actual else span
        # a --generate may have resized the VO clip in place WITHOUT rippling (span < audio) —
        # clamp the beat span so consecutive lines can never overlap
        if actual and i<len(vos)-1: newspan=max(newspan, actual+GAP)
        newB.append(round(newB[-1]+newspan,3))
    def warp(t):
        for i in range(len(oldB)-1):
            if t<=oldB[i+1]+1e-9 or i==len(oldB)-2:
                a0,a1,b0,b1=oldB[i],oldB[i+1],newB[i],newB[i+1]
                if t<oldB[0]: return t
                u=(t-a0)/(a1-a0) if a1>a0 else 0
                return b0+u*(b1-b0)
        return t
    n=0
    for cid,c in p["clips"].items():
        s,e=c["start"],c["start"]+c["dur"]
        ns,ne=warp(s),warp(e)
        if abs(ns-s)>1e-4 or abs(ne-e)>1e-4:
            for arr in c.get("keyframes",{}).values():
                for k in arr:
                    if "t" in k: k["t"]=round(warp(k["t"]),3)
            c["start"],c["dur"]=round(ns,3),round(max(0.2,ne-ns),3); n+=1
    for cid,c in vos:   # VO clips get EXACT audio duration (not warped end); splits keep theirs
        if is_split(c): continue
        ad=p.get("assets",{}).get(c.get("asset",""),{})
        actual=ad.get("meta",{}).get("duration")
        if actual: c["dur"]=round(actual,3)
    save(p,a.out or a.project); print(f"retimed {n} clips against {len(vos)} VO lines -> total {total(p):.1f}s")

# ── adopt: reuse GENERATED assets from another project by matching line text — a rebuild/remix
# keeps the hand-tuned VO takes (and their viseme tracks) instead of regenerating everything.
# Beat pairing: bNN_vo ↔ bNN_av (the skeleton compiler's ids); non-skeleton avatars match by overlap. ──
def _norm_text(t): return re.sub(r"\s+"," ",(t or "").strip())
def _spoken_two(n):
    ones=["zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve",
          "thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen"]
    tens=["","","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety"]
    return ones[n] if n<20 else tens[n//10]+("-"+ones[n%10] if n%10 else "")
def _tts_norm(t):
    """mirror of the editor's tts_normalize (speech_params): standalone 4-digit years → words,
    so lint/adopt can match authored text against the normalized text stored on generated assets."""
    def year(m):
        y=int(m.group(0)); hi,lo=y//100,y%100
        if 2000<=y<2010: return "two thousand "+_spoken_two(lo) if lo else "two thousand"
        if lo==0: return _spoken_two(hi)+" hundred"
        if lo<10: return _spoken_two(hi)+" oh "+_spoken_two(lo)
        return _spoken_two(hi)+" "+_spoken_two(lo)
    return re.sub(r"(?<![0-9A-Za-z])[12][0-9]{3}(?![0-9A-Za-z])", year, t or "")
def cmd_adopt(p, a):
    src=load(a.src)
    speech={}; vis={}
    for ak,ad in src.get("assets",{}).items():
        if ad.get("status")!="ready" or not ad.get("uri"): continue
        if not os.path.exists(resolve_uri(ad["uri"])): continue   # stale entry whose cache file is gone
        if ad.get("type")=="speech":
            k=_norm_text(ad.get("params",{}).get("text"))
            speech.setdefault(k,(ak,ad)); speech.setdefault(_norm_text(_tts_norm(k)),(ak,ad))
        if ad.get("type")=="visemes": vis.setdefault(_norm_text(ad.get("params",{}).get("dialog")),(ak,ad))
    nv=na=0
    for cid,c in p["clips"].items():
        if p["rows"].get(c.get("row",""),{}).get("type")!="tts": continue
        key=_norm_text(c.get("params",{}).get("text"))
        hit=speech.get(key) or speech.get(_norm_text(_tts_norm(key)))
        if hit:
            ak,ad=hit; p["assets"][ak]=ad; c["asset"]=ak; nv+=1
            m=re.match(r"(b\d+)_vo$",cid)   # pair the beat's avatar clip with the matching viseme track
            if m and key in vis and f"{m.group(1)}_av" in p["clips"]:
                vk,vd=vis[key]; p["assets"][vk]=vd; p["clips"][f"{m.group(1)}_av"]["asset"]=vk; na+=1
    save(p,a.out or a.project)
    print(f"adopted {nv} VO takes + {na} viseme tracks from {a.src} (genvo fills the rest)")

# ── genvo: bulk-generate every pending VO line + host viseme track via the headless editor,
# then retime. The one command between "skeleton compiled" and "watchable cut". ──
def cmd_genvo(a):
    exe=a.exe or "./build/slopstudio.exe"
    for phase,rt in (("VO","tts"),("visemes","avatar")):
        p=load(a.project)   # reload — the editor writes the file after each gen
        todo=[]
        for cid,c in sorted(p["clips"].items(), key=lambda kv: kv[1].get("start",0)):
            if p["rows"].get(c.get("row",""),{}).get("type")!=rt: continue
            if rt=="tts" and not c.get("params",{}).get("text"): continue
            ak=c.get("asset"); ad=p.get("assets",{}).get(ak) if ak else None
            if ad and ad.get("status")=="ready" and ad.get("uri"):
                if os.path.exists(resolve_uri(ad["uri"])): continue   # regenerate if the cache file was pruned
            todo.append(cid)
        print(f"genvo: {len(todo)} {phase} clips to generate")
        for i,cid in enumerate(todo):
            r=subprocess.run([exe,a.project,"--generate",cid],capture_output=True,text=True)
            ok = r.returncode==0
            print(f"  [{i+1}/{len(todo)}] {cid}: {'ok' if ok else 'FAILED'}")
            if not ok:
                tail = (r.stderr or r.stdout).strip().splitlines()
                print("    "+ (tail[-1] if tail else "(no output)"))
    p=load(a.project); cmd_retime(p, argparse.Namespace(out=a.project, project=a.project))

def main():
    ap=argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub=ap.add_subparsers(dest="cmd", required=True)
    def common(s): s.add_argument("project"); s.add_argument("--out", default=None)
    s=sub.add_parser("overview"); common(s)
    for name in ("add","insert"):
        s=sub.add_parser(name); common(s)
        s.add_argument("--type", required=True); s.add_argument("--row", default=None)
        s.add_argument("--id", default=None); s.add_argument("--dur", type=float, default=None,
                       help="clip duration (s); default 4.0, or 2.0 for blur transitions")
        s.add_argument("--start", type=float, default=None); s.add_argument("--at", type=float, default=None)
        s.add_argument("-p","--param", action="append", default=[], help="key=value (JSON value)")
        s.add_argument("--asset", default=None, help="reference an existing asset key")
        s.add_argument("--asset-uri", dest="asset_uri", default=None,
                       help="register a NEW image/video asset at this uri + point the clip at it")
        s.add_argument("--pos", default=None, help="transform pos 'x,y' (1080p, center-relative)")
        s.add_argument("--scale", default=None, help="transform scale (one number, or 'sx,sy')")
    s=sub.add_parser("set"); common(s); s.add_argument("clip"); s.add_argument("kv", nargs="+", help="dotted.key=value")
    s=sub.add_parser("reasset"); common(s); s.add_argument("clip")
    s.add_argument("--uri", required=True, help="image/video file to point the clip at")
    s.add_argument("--key", default=None, help="asset key (default: a fresh clip-derived key, so shared assets aren't clobbered)")
    s.add_argument("--type", default=None, choices=["image","video"], help="asset type (default: infer from the row)")
    s=sub.add_parser("rowset"); common(s); s.add_argument("row"); s.add_argument("kv", nargs="+", help="param=value (JSON value) — lane params: gain_db, normalize, normalize_db, voice_preset, driven_by, rig")
    s=sub.add_parser("kfprune"); common(s); s.add_argument("--clip", default=None, help="limit to one clip")
    s.add_argument("--keep-opacity", action="store_true", help="keep redundant opacity-fade tracks (the default transition handles fades)")
    s.add_argument("--dry", action="store_true", help="report only, don't write")
    s=sub.add_parser("mv"); common(s); s.add_argument("clip"); s.add_argument("--to",type=float); s.add_argument("--by",type=float); s.add_argument("--ripple",action="store_true")
    s=sub.add_parser("trim"); common(s); s.add_argument("clip"); s.add_argument("--dur",type=float); s.add_argument("--start",type=float); s.add_argument("--no-ripple",action="store_true")
    s=sub.add_parser("rm"); common(s); s.add_argument("clip"); s.add_argument("--ripple",action="store_true")
    s=sub.add_parser("splitaudio"); common(s); s.add_argument("clip"); s.add_argument("--row", default="r_vidaud",
        help="split a video clip's audio out to an editable audio track (extracts a wav, mutes the video clip's intrinsic audio)")
    s=sub.add_parser("ripple"); common(s); s.add_argument("--at",type=float,required=True); s.add_argument("--by",type=float,required=True)
    s=sub.add_parser("rebase"); common(s)
    s=sub.add_parser("addtrack"); common(s); s.add_argument("--row",required=True); s.add_argument("--type",required=True)
    s.add_argument("--name",default=None); s.add_argument("--before",default=None); s.add_argument("--after",default=None)
    s=sub.add_parser("mvtrack"); common(s); s.add_argument("--track",required=True)
    g=s.add_mutually_exclusive_group(required=True); g.add_argument("--up",action="store_true"); g.add_argument("--down",action="store_true")
    s=sub.add_parser("transition"); common(s); s.add_argument("clip")
    s.add_argument("--preset", required=True, choices=list(PRESETS))
    s.add_argument("--in", dest="indur", type=float, default=0.9); s.add_argument("--no-out", action="store_true")
    s=sub.add_parser("template"); common(s); s.add_argument("name", choices=list(TEMPLATES))
    s.add_argument("--at", type=float, required=True); s.add_argument("--dur", type=float, default=8.0)
    s.add_argument("--shot", default=None); s.add_argument("--shot-file", dest="shotfile", default=None)
    s.add_argument("--text", default=None); s.add_argument("--emotion", default="happy")
    s.add_argument("--bg", action="store_true"); s.add_argument("--pose", default="neutral")
    s=sub.add_parser("skeleton", help="compile a beat-list skeleton into a full project")
    s.add_argument("skeleton"); s.add_argument("--out", required=True)
    s=sub.add_parser("lint", help="catch gaps / repeats / stale VO / missing assets / overlaps"); common(s)
    s=sub.add_parser("adopt", help="reuse generated VO/viseme assets from another project by text match"); common(s)
    s.add_argument("--src", required=True, help="project to adopt generated assets from")
    s=sub.add_parser("retime", help="snap the timeline to real generated VO durations (time-warp)"); common(s)
    s=sub.add_parser("genvo", help="bulk-generate pending VO + visemes headlessly, then retime")
    s.add_argument("project"); s.add_argument("--exe", default=None, help="editor binary (default ./build/slopstudio.exe)")
    a=ap.parse_args()

    if a.cmd=="skeleton": cmd_skeleton(a); return
    if a.cmd=="genvo": cmd_genvo(a); return
    p=load(a.project); out=a.out or a.project

    if a.cmd=="lint": sys.exit(cmd_lint(p,a))
    if a.cmd=="adopt": cmd_adopt(p,a); return
    if a.cmd=="retime": cmd_retime(p,a); return

    if a.cmd=="overview": cmd_overview(p,a); return

    if a.cmd in ("add","insert"):
        row=a.row or ROW_OF.get(a.type,"r_img")
        params=OD()
        for kv in a.param:
            k,_,v=kv.partition("="); params[k]=jval(v)
        start = a.at if a.at is not None else (a.start if a.start is not None else total(p))
        dur = a.dur if a.dur is not None else (2.0 if a.type=="blur" else 4.0)  # blur transitions default short
        if a.cmd=="insert":   # make room: ripple everything at/after `start` by dur
            ripple(p, start, dur, after=True)
        cid=new_clip(p,a.type,row,start,dur,params,a.id)
        c=p["clips"][cid]
        # media: register/point at an asset (image|video)
        akey=a.asset
        if a.asset_uri:
            akey = a.asset or (a.id or cid).replace("c_","")+"_asset"
            atype = "video" if a.type=="video" else "image"
            p.setdefault("assets",OD())[akey]=OD([("provider","external"),("type",atype),
                ("status","ready"),("uri",a.asset_uri),("meta",OD())])
        if akey: c["asset"]=akey
        if a.pos is not None:
            c["transform"]["pos"]=[float(x) for x in a.pos.split(",")]
        if a.scale is not None:
            sv=[float(x) for x in a.scale.split(",")]; c["transform"]["scale"]=sv*2 if len(sv)==1 else sv
        save(p,out); print(f"{'inserted' if a.cmd=='insert' else 'added'} {cid} ({a.type}{', asset='+akey if akey else ''}) on {row} @ {start:.2f} dur {a.dur} -> total {total(p):.1f}s")
        return

    if a.cmd=="set":
        c=p["clips"][a.clip]
        for kv in a.kv:
            k,_,v=kv.partition("=")
            if k=="row":                       # move the clip to another row (fixes the clip-array too)
                for r in p["rows"].values():
                    if a.clip in r.get("clips",[]): r["clips"].remove(a.clip)
                ensure_row(p,v); p["rows"][v]["clips"].append(a.clip); c["row"]=v
            else: set_dotted(c,k,jval(v))
        save(p,out); print(f"set {a.clip}: {', '.join(a.kv)}"); return

    if a.cmd=="reasset":
        c=p["clips"][a.clip]
        key=a.key or (a.clip.replace("c_","")+"_img")   # fresh key by default → won't clobber a shared asset
        atype=a.type or ("video" if p["rows"].get(c.get("row",""),{}).get("type")=="video" else "image")
        p.setdefault("assets",OD())[key]=OD([("provider","external"),("type",atype),
            ("status","ready"),("uri",a.uri),("meta",OD())])
        c["asset"]=key
        save(p,out); print(f"reasset {a.clip} -> {key} ({atype}) {a.uri}"); return

    if a.cmd=="rowset":
        if a.row not in p["rows"]: print(f"no row {a.row}"); return
        params=p["rows"][a.row].setdefault("params",OD())
        for kv in a.kv:
            k,_,v=kv.partition("="); params[k]=jval(v)
        save(p,out); print(f"rowset {a.row}: {dict(params)}"); return

    if a.cmd=="kfprune":
        # Remove keyframe tracks that are now redundant: (1) no-ops (<=1 kf, or all values
        # identical), and (2) pure opacity FADES ([0,1,1,0] etc.) — the compositor's default
        # transition already does fade-in/out (and even suppresses itself when a manual opacity
        # kf exists), so these are leftovers from before default transitions. pos/scale kept
        # (those are intentional motion: pop-ins, title slides, Ken-Burns).
        def is_fade(vals):
            sc=[v for v in vals if not isinstance(v,list)]
            return bool(sc) and all(v in (0,0.0,1,1.0) for v in sc) and any(v in (0,0.0) for v in sc)
        removed=[]
        for cid,c in p["clips"].items():
            if a.clip and cid!=a.clip: continue
            kf=c.get("keyframes")
            if not kf: continue
            for path in list(kf.keys()):
                vals=[k.get("v") for k in kf[path]]
                flat=[tuple(v) if isinstance(v,list) else v for v in vals]
                noop = len(kf[path])<=1 or len(set(map(str,flat)))==1
                fade = (path.split(".")[-1]=="opacity") and (not a.keep_opacity) and is_fade(vals)
                if noop or fade: removed.append((cid,path,"noop" if noop else "fade"))
            if not a.dry:
                for cid2,path,_ in [r for r in removed if r[0]==cid]: kf.pop(path,None)
                if not kf: c.pop("keyframes",None)
        if not a.dry: save(p,out)
        print(f"kfprune{' (dry)' if a.dry else ''}: {len(removed)} keyframe tracks "
              f"({sum(1 for r in removed if r[2]=='fade')} fades, {sum(1 for r in removed if r[2]=='noop')} no-ops)")
        for cid,path,why in removed: print(f"  {cid:14s} {path:20s} {why}")
        return

    if a.cmd=="addtrack":
        rid=a.row
        if rid not in p["rows"]:
            p["rows"][rid]=OD([("type",a.type),("name",a.name or rid),("params",OD()),("clips",[])])
        tid=rid.replace("r_","tk_")
        if not any(rid in t.get("rows",[]) for t in p["tracks"]):
            tr=OD([("id",tid),("name",a.name or rid),("kind","audio" if a.type in ("tts","music") else "video"),("rows",[rid])])
            pos=len(p["tracks"])
            if a.before: pos=next((i for i,t in enumerate(p["tracks"]) if a.before in t.get("rows",[])),pos)
            if a.after:  pos=next((i+1 for i,t in enumerate(p["tracks"]) if a.after in t.get("rows",[])),pos)
            p["tracks"].insert(pos,tr)
        save(p,out); print(f"track {tid}/{rid} ({a.type}) ready; tracks: {[t['id'] for t in p['tracks']]}"); return

    if a.cmd=="mvtrack":
        idx=next((i for i,t in enumerate(p["tracks"]) if t["id"]==a.track or a.track in t.get("rows",[])),None)
        if idx is None: print("track not found"); return
        j=idx+(-1 if a.up else 1)
        if 0<=j<len(p["tracks"]): p["tracks"][idx],p["tracks"][j]=p["tracks"][j],p["tracks"][idx]
        save(p,out); print(f"moved track {a.track} {'up' if a.up else 'down'}; order: {[t['id'] for t in p['tracks']]}"); return

    if a.cmd=="mv":
        c=p["clips"][a.clip]; old=c["start"]
        d = (a.by if a.by is not None else (a.to-old))
        if a.ripple: shift_clip(c,d); ripple(p, old, d, except_id=a.clip, after=(d>0)); reb=rebase(p)
        else: shift_clip(c,d); reb=0
        if c["start"]<0: rebase(p)
        save(p,out); print(f"moved {a.clip} by {d:+.2f} -> {c['start']:.2f}" + (f" (rebased +{reb:.2f})" if reb else "")); return

    if a.cmd=="trim":
        c=p["clips"][a.clip]; rip = not a.no_ripple
        if a.dur is not None:
            d=a.dur-c["dur"]; endBefore=c["start"]+c["dur"]; c["dur"]=round(a.dur,3)
            if rip: ripple(p, endBefore, d, except_id=a.clip, after=True)
        if a.start is not None:
            d=a.start-c["start"]; startBefore=c["start"]; c["start"]=round(a.start,3); c["dur"]=round(c["dur"]-d,3)
            if rip: ripple(p, startBefore, d, except_id=a.clip, after=False)
        rebase(p); save(p,out); print(f"trimmed {a.clip} -> start {c['start']:.2f} dur {c['dur']:.2f}, total {total(p):.1f}s"); return

    if a.cmd=="rm":
        c=p["clips"].pop(a.clip)
        for r in p["rows"].values():
            if a.clip in r.get("clips",[]): r["clips"].remove(a.clip)
        if a.ripple: ripple(p, c["start"], -(c["dur"]), after=True); rebase(p)
        save(p,out); print(f"removed {a.clip}, total {total(p):.1f}s"); return

    if a.cmd=="splitaudio":
        c=p["clips"].get(a.clip)
        if not c: print(f"no clip {a.clip}"); return
        asset=p.get("assets",{}).get(c.get("asset",""),{})
        src=asset.get("src") or asset.get("uri")
        if not src: print(f"{a.clip} has no video source asset"); return
        os.makedirs("cache/audio", exist_ok=True)
        wav=f"cache/audio/{a.clip}.wav"
        r=subprocess.run(["ffmpeg","-y","-i",resolve_uri(src),"-vn","-ac","1","-ar","48000",wav], capture_output=True)
        if r.returncode!=0 or not os.path.exists(wav):
            print("ffmpeg audio-extract failed (run inside `nix develop`?):\n"+r.stderr.decode("utf-8","replace")[-600:]); return
        ensure_audio_row(p, a.row)
        akey=f"{a.clip}_audio"
        p.setdefault("assets",OD())[akey]=OD([("provider","external"),("type","audio"),
            ("status","ready"),("uri",wav),("meta",OD())])
        cid=new_clip(p,"music",a.row,c.get("start",0.0),c.get("dur",4.0),
                     OD([("in",c.get("params",{}).get("in",0.0)),("from_video",a.clip)]),
                     cid=f"c_{a.clip}_aud")
        p["clips"][cid]["asset"]=akey
        c.setdefault("params",OD())["mute_audio"]=True
        save(p,out); print(f"split audio of {a.clip} -> {wav} (clip {cid} on {a.row}); muted the source video"); return

    if a.cmd=="ripple":
        ripple(p, a.at, a.by, after=True); rebase(p); save(p,out); print(f"rippled @ {a.at} by {a.by:+.2f}, total {total(p):.1f}s"); return

    if a.cmd=="rebase":
        sh=rebase(p); save(p,out); print(f"rebased (+{sh:.2f}), earliest now 0, total {total(p):.1f}s"); return

    if a.cmd=="transition":
        apply_transition(p, a.clip, a.preset, a.indur, not a.no_out)
        save(p,out); print(f"applied transition '{a.preset}' to {a.clip} (in {a.indur}s)"); return

    if a.cmd=="template":
        shot=a.shot
        if a.shotfile:
            shot="shot_"+re.sub(r'[^a-z0-9]','', a.shotfile.lower().split('/')[-1].rsplit('.',1)[0])[:14]
            add_asset(p, shot, a.shotfile)
        if not shot: print("need --shot KEY or --shot-file PATH"); return
        TEMPLATES[a.name](p, a.at, a.dur, shot, a.text, a.emotion, a.bg, a.pose)
        save(p,out); print(f"instantiated '{a.name}' template @ {a.at} dur {a.dur}s, total {total(p):.1f}s"); return

if __name__=="__main__": main()
